alter table CARSERVICE_INDIVIDUAL add constraint FK_CARSERVICE_INDIVIDUAL_ON_ID foreign key (ID) references CARSERVICE_CUSTOMER(ID) on delete CASCADE;
create unique index IDX_CARSERVICE_INDIVIDUAL_UNIQ_PASSPORT_NO on CARSERVICE_INDIVIDUAL (PASSPORT_NO) ;
