create unique index IDX_CARSERVICE_CUSTOMER_UNIQ_PHONE on CARSERVICE_CUSTOMER (PHONE) ;
create unique index IDX_CARSERVICE_CUSTOMER_UNIQ_INN on CARSERVICE_CUSTOMER (INN) ;
create unique index IDX_CARSERVICE_CUSTOMER_UNIQ_EMAIL on CARSERVICE_CUSTOMER (EMAIL) ;
create unique index IDX_CARSERVICE_CUSTOMER_UNIQ_PASSPORT_NO on CARSERVICE_CUSTOMER (PASSPORT_NO) ;
