alter table CARSERVICE_REPAIR add constraint FK_CARSERVICE_REPAIR_ON_CENTER foreign key (CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID);
create index IDX_CARSERVICE_REPAIR_ON_CENTER on CARSERVICE_REPAIR (CENTER_ID);
