-- begin CARSERVICE_CUSTOMER
create unique index IDX_CARSERVICE_CUSTOMER_UK_EMAIL on CARSERVICE_CUSTOMER (EMAIL) where DELETE_TS is null ^
create unique index IDX_CARSERVICE_CUSTOMER_UK_PHONE on CARSERVICE_CUSTOMER (PHONE) where DELETE_TS is null ^
-- end CARSERVICE_CUSTOMER
-- begin CARSERVICE_COMPANY
alter table CARSERVICE_COMPANY add constraint FK_CARSERVICE_COMPANY_ON_ID foreign key (ID) references CARSERVICE_CUSTOMER(ID) on delete CASCADE^
create unique index IDX_CARSERVICE_COMPANY_UK_INN on CARSERVICE_COMPANY (INN) where DELETE_TS is null ^
-- end CARSERVICE_COMPANY
-- begin CARSERVICE_INDIVIDUAL
alter table CARSERVICE_INDIVIDUAL add constraint FK_CARSERVICE_INDIVIDUAL_ON_ID foreign key (ID) references CARSERVICE_CUSTOMER(ID) on delete CASCADE^
create unique index IDX_CARSERVICE_INDIVIDUAL_UK_PASSPORT_NO on CARSERVICE_INDIVIDUAL (PASSPORT_NO) where DELETE_TS is null ^
-- end CARSERVICE_INDIVIDUAL
-- begin CARSERVICE_CITY
create unique index IDX_CARSERVICE_CITY_UK_NAME on CARSERVICE_CITY (NAME) where DELETE_TS is null ^
create unique index IDX_CARSERVICE_CITY_UK_CODE on CARSERVICE_CITY (CODE) where DELETE_TS is null ^
-- end CARSERVICE_CITY
-- begin CARSERVICE_CAR_SERVICE_CENTER
alter table CARSERVICE_CAR_SERVICE_CENTER add constraint FK_CARSERVICE_CAR_SERVICE_CENTER_ON_CITY foreign key (CITY_ID) references CARSERVICE_CITY(ID)^
create index IDX_CARSERVICE_CAR_SERVICE_CENTER_ON_CITY on CARSERVICE_CAR_SERVICE_CENTER (CITY_ID)^
-- end CARSERVICE_CAR_SERVICE_CENTER
-- begin CARSERVICE_EMPLOYEE
alter table CARSERVICE_EMPLOYEE add constraint FK_CARSERVICE_EMPLOYEE_ON_CENTER foreign key (CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
create unique index IDX_CARSERVICE_EMPLOYEE_UK_FIRST_NAME on CARSERVICE_EMPLOYEE (FIRST_NAME) where DELETE_TS is null ^
create unique index IDX_CARSERVICE_EMPLOYEE_UK_LAST_NAME on CARSERVICE_EMPLOYEE (LAST_NAME) where DELETE_TS is null ^
create index IDX_CARSERVICE_EMPLOYEE_ON_CENTER on CARSERVICE_EMPLOYEE (CENTER_ID)^
-- end CARSERVICE_EMPLOYEE
-- begin CARSERVICE_REPAIR
alter table CARSERVICE_REPAIR add constraint FK_CARSERVICE_REPAIR_ON_CENTER foreign key (CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
create index IDX_CARSERVICE_REPAIR_ON_CENTER on CARSERVICE_REPAIR (CENTER_ID)^
-- end CARSERVICE_REPAIR
-- begin CARSERVICE_CAR_SERVICE_CENTER_CUSTOMER_LINK
alter table CARSERVICE_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references CARSERVICE_CAR_SERVICE_CENTER(ID)^
alter table CARSERVICE_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_ON_CUSTOMER foreign key (CUSTOMER_ID) references CARSERVICE_CUSTOMER(ID)^
-- end CARSERVICE_CAR_SERVICE_CENTER_CUSTOMER_LINK
-- begin CARSERVICE_REPAIR_EMPLOYEE_LINK
alter table CARSERVICE_REPAIR_EMPLOYEE_LINK add constraint FK_REPEMP_ON_REPAIR foreign key (REPAIR_ID) references CARSERVICE_REPAIR(ID)^
alter table CARSERVICE_REPAIR_EMPLOYEE_LINK add constraint FK_REPEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CARSERVICE_EMPLOYEE(ID)^
-- end CARSERVICE_REPAIR_EMPLOYEE_LINK
